name: Generate GitHub Snake

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake animation
        uses: actions/checkout@v4

      - name: Generate snake gif
        uses: coderaiser/github-action-gif@v1.1.18
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: dist/github-snake.gif

      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
